# Generated by Django 4.0 on 2022-01-03 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='djangoClasses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=40)),
                ('courseNumber', models.IntegerField(blank=True, default='', max_length=5)),
                ('instructorName', models.CharField(blank=True, default='', max_length=40)),
                ('duration', models.DecimalField(decimal_places=2, default=0.0, max_digits=10000)),
            ],
        ),
    ]
