# Generated by Django 4.0 on 2022-01-03 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classApp', '0002_alter_djangoclasses_coursenumber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='djangoclasses',
            old_name='courseNumber',
            new_name='course_number',
        ),
        migrations.RenameField(
            model_name='djangoclasses',
            old_name='instructorName',
            new_name='instructor_name',
        ),
    ]
